<?php
$ID=null;
			if(isset($_POST['p1'])){
				$ID=1;
			}
			if(isset($_POST['p2'])){
				$ID=2;
			}
			if(isset($_POST['p3'])){
				$ID=3;
			}
			if(isset($_POST['p4'])){
				$ID=4;
			}
			if(isset($_POST['p5'])){
				$ID=5;
			}
			if(isset($_POST['p6'])){
				$ID=6;
			}
			if(isset($_POST['pro1'])){
				$ID=7;
			}
			if(isset($_POST['pro2'])){
				$ID=8;
			}
			if(isset($_POST['pro3'])){
				$ID=9;
			}
			if(isset($_POST['pro4'])){
				$ID=10;
			}
			if(isset($_POST['pro5'])){
				$ID=11;
			}
			if(isset($_POST['pro6'])){
				$ID=12;
			}
			if(isset($_POST['pro7'])){
				$ID=13;
			}
			if(isset($_POST['pro8'])){
				$ID=14;
			}
			if(isset($_POST['pro9'])){
				$ID=15;
			}
			if(isset($_POST['pro10'])){
				$ID=16;
			}
			if(isset($_POST['pro11'])){
				$ID=17;
			}
			if(isset($_POST['pro12'])){
				$ID=18;
			}

			if(isset($_POST['pro13'])){
				$ID=19;
			}
			if(isset($_POST['pro14'])){
				$ID=20;
			}
			if(isset($_POST['pro15'])){
				$ID=21;
			}
		?>
	<?php include "sell.php"; ?>
